server:
  port: 10060
spring:
  application:
    name: user-server
  datasource:
    username: root
    password: Wc1107556051.
    url: jdbc:mysql://127.0.0.1:3306/miniblibli?serverTimezone=Asia/Shanghai&charactor

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
